config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :leases do
    put '/accept-lease', to: 'leases#accept_lease'
  end

  resources :financials
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :user_signed_in?
  before_action :manager_or_owner_auth, only: [:update, :edit]
  before_action :lease_accepted_by_all?, only: [:update, :edit]

  def index
    @leases = current_user.leases
  end

  def new
    redirect_to root_path if !current_user || !current_user.role == 'owner'
  end

  def create
    @lease = current_user.leases.create(lease_params)
    if @lease
      flash['success'] = "New lease succesfully created"
      redirect_to lease_path(@lease)
    else
      flash[:danger] = @lease.errors.full_messages.join(", ")
      redirect_back fallback_location: new_lease_path
    end
  end

  def show
    @lease = current_user.leases.find_by_id(params[:id])
    redirect_to root_path if @lease.nil?
  end

  def edit
    redirect_to lease_path(lease) if current_user.tenant?
  end

  def update
    if params[:manager_email]
      @lease.add_user('manager', params[:manager_email])
    elsif params[:tenant_email]
      @lease.add_user('tenant', params[:tenant_email])
    else
      @lease.update(lease_params)
    end
    redirect_to lease_path(@lease)
  end

  def accept_lease
    current_user.find_acceptance_by_lease(Lease.find(params[:lease_id])).update(accepted: true)
    redirect_back fallback_location: lease_path(params[:lease_id])
  end

  private

  def lease_params
    params.require(:lease).permit(
     :amount,
     :starts_at,
     :ends_at,
     :address_line_1,
     :address_line_2,
     :payment_day,
     :zip,
     :city,
     :state)
  end

  def manager_or_owner_auth
    @lease = current_user.leases.find_by_id(params[:id])
    redirect_to lease_path(@lease) if current_user.tenant?
  end

  def lease_accepted_by_all?
    @lease = current_user.leases.find_by_id(params[:id])
    if @lease && @lease.accepted_by_all?
      flash[:danger] = "The lease has been accepted by all tenants. It can no longer be updated"
      redirect_to lease_path @lease
    end
  end

end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/edit.html.erb
<h1>Edit Lease</h1>

<%= form_for @lease do |f| %>
  <div class="form-group">
    Address Line 1: <%= f.text_field :address_line_1, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Address Line 2: <%= f.text_field :address_line_2, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    City: <%= f .text_field :city, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    State: <%= f.text_field :state, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Zip: <%= f.text_field :zip, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Start Date: <%= f.date_select :starts_at, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    End Date: <%= f.date_select :ends_at, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Rent Amount: <%= f.number_field :amount, class: 'form-control', step: 0.01 %><br>
  </div>
  <div class="form-group">
    Rent Payment Day (will default to last day of month for months shorter than 31 days): <%= f.select :payment_day, Array(1..31), {}, {class: 'form-control'} %><br>
  </div>
  <%= f.submit "Save Changes", class: 'btn btn-success' %>
<% end %>

app/views/leases/index.html.erb
<div class="col">
  <h1>Your leases</h1>
  <table class="table">
    <thead>
      <td>Address</td>
      <td></td>
    </thead>
    <tbody>
      <% @leases.each do |l| %>
        <tr>
          <td> <%= l.address_line_1 %><br><%= l.address_line_2 %><br><%= l.city %> <br> <%= link_to 'Lease Details', lease_path(l) %> </td>
          <td>
            <% if current_user.tenant? && !current_user.find_acceptance_by_lease(l).accepted %>
            <%= form_tag lease_accept_lease_path(l), method: :put do %>
            <%= submit_tag 'Accept Lease', class: 'btn btn-success' %>
            <% end %>
            <% elsif current_user.tenant? && current_user.find_acceptance_by_lease(l).accepted %>
            <b>Lease Accepted</b>
            <% elsif !current_user.tenant? && l.updatable? %>
            <%= link_to 'Edit Lease', edit_lease_path(l), class: 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/leases/new.html.erb
<h1>Signup!</h1>

<%= form_for :lease, url: '/leases' do |f| %>
  <div class="form-group">
    Address Line 1: <%= f.text_field :address_line_1, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Address Line 2: <%= f.text_field :address_line_2, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    City: <%= f .text_field :city, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    State: <%= f.text_field :state, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Zip: <%= f.text_field :zip, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Start Date: <%= f.date_select :starts_at, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    End Date: <%= f.date_select :ends_at, class: 'form-control' %><br>
  </div>
  <div class="form-group">
    Rent Amount: <%= f.number_field :amount, class: 'form-control', step: 0.01 %><br>
  </div>
  <div class="form-group">
    Rent Payment Day (will default to last day of month for months shorter than 31 days): <%= f.select :payment_day, Array(1..31), {}, {class: 'form-control'} %><br>
  </div>
  <%= f.submit "Create New Lease", class: 'btn btn-success' %>
  <% end %>

app/views/leases/show.html.erb
<div class="row">
  <div class="card col">
    <h1 class="card-title">Lease Details</h1>
    <div class="card-text">
      <p><b>Address:</b></p>
      <p> <%= @lease.address_line_1 %> </p>
      <p> <%= @lease.address_line_2 %> </p>
      <p> <%= @lease.city %>, <%= @lease.state %> </p>
      <p> <%= @lease.zip %> </p>
      <p><b>Rent:</b></p>
      <p> <%= @lease.amount %> </p>
      <p><b>Start Date:</b></p>
      <p> <%= @lease.starts_at %> </p>
      <p><b>End Date:</b></p>
      <p> <%= @lease.ends_at %> </p>
    </div>
    <% if current_user.tenant? && !current_user.find_acceptance_by_lease(@lease).accepted %>
      <%= form_tag lease_accept_lease_path(@lease), method: :put do %>
        <%= submit_tag 'Accept Lease', class: 'btn btn-success' %>
      <% end %>
    <% elsif current_user.tenant? && current_user.find_acceptance_by_lease(@lease).accepted %>
      <b>Lease Accepted</b>
    <% end %>
  </div>

  <div class="card col">
    <h1 class="card-title">Managers</h1>
    <div class="card-text">
      <% @lease.managers.each do |m| %>
        <p> <%= m.name %> <%= m.email %> </p>
      <% end %>

      <% if current_user.owner? %>
        <p><b>Add by Email:</b></p>
        <%= form_tag lease_path, method: :put do %>
          <%= text_field_tag :manager_email %>
          <%= submit_tag 'Add Manager to Lease', class: 'btn btn-success' %>
        <% end %>
      <% end %>

    </div>
  </div>

  <div class="card col">
    <h1 class="card-title">Tenants</h1>
    <div class="card-text">
      <% @lease.acceptances.each do |a| %>
        <p> <%= a.tenant.name %> | <%= a.tenant.email %> | <%= a.accepted ? 'Accepted' : "Pending acceptance" %></p>
      <% end %>
      <% if current_user.owner? %>
        <p><b>Add by Email:</b></p>
        <%= form_tag lease_path, method: :put do %>
          <%= text_field_tag :tenant_email %>
          <%= submit_tag 'Add Tenant to Lease',  class: 'btn btn-success' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @lease.invited_users.count > 0 %>
    <div class="card col">
      <h1 class="card-title">Invited users with no account</h1>
      <div class="card-text">
        <% @lease.invited_users.each do |u| %>
          <p> <%= u.role %> <%= u.email %> </p>
        <% end %>
      </div>
    </div>
  <% end %>

</div>