config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :leases do
    put '/accept-lease', to: 'leases#accept_lease'
  end

  resources :financials
end

app/controllers/financials_controller.rb
class FinancialsController < ApplicationController
  before_action :manager_or_owner_auth

  def index
    @financials = Financials.new(current_user)
  end

  def show
    @lease = current_user.leases.find_by_id(params[:id])
  end

  private

  def manager_or_owner_auth
    redirect_to root_path if !current_user || current_user.tenant?
  end

end

app/helpers/financial_helper.rb
module FinancialHelper
end

app/views/financials/index.html.erb
<div class="col">
  <h1>Revenue Detail By Lease</h1>
  <% current_user.leases.each do |lease| %>
    <p><b><%= link_to "#{lease.address_line_1}, #{lease.address_line_2}", financial_path(lease) %></b></p>
  <% end %>
  <hr class="my-4">
  <h1>Total Revenue</h1>
  <% @financials.totals_by_month_year.each do |year, months| %>
    <table class="table">
      <h2> <%= year %> </h2>
      <thead>
        <th>Month</th>
        <th>Expected Revenue</th>
      </thead>
      <tbody>
        <% months.each do |month, revenue| %>
          <tr>
            <td> <%= month %> </td>
            <td> <%= revenue %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/financials/show.html.erb
<div class="col">
  <h1>Revenue Detail By Lease</h1>
    <p><b><%= link_to "#{@lease.address_line_1}, #{@lease.address_line_2} (click for lease details)", lease_path(@lease) %></b></p>
  <hr class="my-4">
  <h1>Total Revenue</h1>
  <% @lease.revenue_by_all_months.each do |year, months| %>
    <table class="table">
      <h2> <%= year %> </h2>
      <thead>
        <th>Month</th>
        <th>Expected Revenue</th>
      </thead>
      <tbody>
        <% months.each do |month, revenue| %>
          <tr>
            <td> <%= month %> </td>
            <td> <%= revenue %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>