config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :leases do
    put '/accept-lease', to: 'leases#accept_lease'
  end

  resources :financials
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lease Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= root_path %>">Lease Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item">
              <a class="nav-link" href="<%= logout_path %>">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= leases_path %>">My Leases</a>
            </li>
            <% if current_user.owner? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_lease_path %>">New Lease</a>
              </li>
            <% end %>
            <% if !current_user.tenant? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= financials_path %>">Financial Dashboard</a>
              </li>
            <% end %>
          <% end %>
          <% if !current_user %>
            <li class="nav-item">
              <a class="nav-link" href="<%= login_path %>">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= signup_path %>">New Account</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="flash">
      <% flash.each do |klass, msg| %>
      <div class="alert alert-<%= klass %>">
        <%= msg %>
      </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>